(async function(){
 let state=ensurePropertyDefaults(getState());
 let dict=await loadLang(state.language||'en');
 const $=s=>document.querySelector(s);
 const currencySelect=$('#currencySelect'); if(currencySelect){currencies.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;currencySelect.appendChild(o)});}
 function t(k){return dict[k]||k}
 function renderText(){document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n)); $('#langToggle').textContent=(state.language||'en').toUpperCase(); $('#themeToggle').textContent=state.theme==='dark'?'Dark mode':'Light mode';}
 async function setLang(lang){state.language=lang; saveState(state); dict=await loadLang(lang); renderText(); renderData();}
 function renderData(){const prop=state.property; if(!prop){$('#registrationCard').classList.remove('hidden'); ['#dashboardCard','#reportCard','#roomBoardCard','#issuesCard','#guestCard','#privacyCard','#docsCard'].forEach(s=>$(s).classList.add('hidden')); return;} $('#registrationCard').classList.add('hidden'); ['#dashboardCard','#reportCard','#roomBoardCard','#issuesCard','#guestCard','#privacyCard','#docsCard'].forEach(s=>$(s).classList.remove('hidden')); $('#propertyTitle').textContent=prop.name; $('#dashboardMeta').textContent=`${todayLabel()} • ${prop.typeLabel}`; const totals=ownerTotals(state, isoToday()); $('#grossToday').textContent=money(totals.gross, totals.currency); $('#expensesToday').textContent=money(totals.expenses, totals.currency); $('#netToday').textContent=money(totals.net, totals.currency); $('#outstandingCount').textContent=money(totals.outstanding, totals.currency); const rr=$('#reportRows'); rr.innerHTML=''; reportSeed.forEach(([key,sub,badge,cls],i)=>{const row=document.createElement('div'); row.className='row'; row.innerHTML=`<div><strong>${['Check-ins Today','Check-outs Today','Room Issues','Inventory Alerts'][i]}</strong><span>${t(key)}</span></div><div class="badge ${cls}">${badge}</div>`; rr.appendChild(row);});
 const extra=document.createElement('div'); extra.className='row'; extra.innerHTML=`<div><strong>Expenses Today</strong><span>Daily expenses recorded and reconciled automatically</span></div><div class="badge clean">${expensesByDate(state, isoToday()).length}</div>`; rr.appendChild(extra);
 const rooms=$('#roomRows'); rooms.innerHTML=''; roomSeed.forEach(r=>{const row=document.createElement('div'); row.className='row'; row.innerHTML=`<div><strong>${r.name}</strong><span>${r.sub}</span></div><div class="badge ${r.status}">${r.status==='avail'?t('available'):r.status==='occ'?t('occupied'):r.status==='clean'?t('cleaning'):t('reserved')}</div>`; rooms.appendChild(row)});
 const issues=$('#issueRows'); issues.innerHTML=''; issueSeed.forEach(r=>{const row=document.createElement('div'); row.className='row'; row.innerHTML=`<div><strong>${r.title}</strong><span>${r.sub}</span></div><div class="badge ${r.status}">${r.status==='good'?t('good_condition'):r.status==='repair'?t('needs_service'):r.status==='service'?t('under_repair'):''}</div>`; issues.appendChild(row)}); $('#issueTemplates').textContent=issueTemplates[prop.type].join(', '); document.querySelector('.privacy').textContent=t('privacy_text');}
 $('#langToggle')?.addEventListener('click',()=>setLang(state.language==='en'?'sw':'en'));
 $('#themeToggle')?.addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';saveState(state);applyTheme(state.theme);renderText();});
 $('#propertyForm')?.addEventListener('submit',e=>{e.preventDefault(); const type=$('#propertyType').value; const typeMap={guest_house:'Guest House',lodge:'Lodge',apartment:'Apartment'}; state.property={name:$('#propertyName').value,owner:$('#ownerName').value,type,currency:$('#currencySelect').value||'TZS',language:$('#languageSelect').value,theme:$('#themeSelect').value,activationCode:$('#activationCode').value,typeLabel:typeMap[type]}; state.language=state.property.language; state.theme=state.property.theme; saveState(state); applyTheme(state.theme); setLang(state.language);});
 if($('#languageSelect')) $('#languageSelect').value=state.language; if($('#themeSelect')) $('#themeSelect').value=state.theme; applyTheme(state.theme); renderText(); renderData();
})();
